version: 2.1

orbs: 
  trivy: donkeycode/trivy@0.0.1

make_php_symfony: &make_php_symfony
  machine:
    image: ubuntu-2204:2022.04.1
  steps:
    - checkout
    - run: echo $DOCKER_PASSWORD | docker login  --username $DOCKER_LOGIN --password-stdin
    - run: make build-php-symfony version=${VERSION}

workflows:
    version: 2.1

    build_php:
      # triggers:
      #   - schedule:
      #       # At 04:05 on Monday.
      #       cron: "5 4 * * 1"
      #       filters:
      #           branches:
      #               only:
      #                   - master

      jobs:
        - build_php_81
        - build_php_80
        - build_php_74

        - trivy/scan:
            name: "Scan and report security"
            context: 
                - org-global
                - rancher-2
            requires:
              - build_php_81
              - build_php_80
              - build_php_74
            images: '"donkeycode/php-nginx-symfony:8.1-fpm" "donkeycode/php-nginx-symfony:7.4-fpm" "donkeycode/php-nginx-symfony:8.0-fpm"'
            files: ''
            mail_subject: "[PublicImages] Rapport de sécurité post update"
            mail_to: "hosting@donkeycode.com"
        
jobs:
    build_php_81:
      <<: *make_php_symfony
      environment:
        VERSION=8.1

    build_php_80:
      <<: *make_php_symfony
      environment:
        VERSION=8.0

    build_php_74:
      <<: *make_php_symfony
      environment:
        VERSION=7.4
