version: 2.1

orbs: 
  trivy: donkeycode/trivy@0.0.1
  docker: donkeycode/docker@0.0.12

make_php_symfony: &make_php_symfony
  machine:
    image: ubuntu-2204:2022.04.1
  steps:
    - checkout
    - docker/login
    - run: make build-php-symfony version=${VERSION}

make_build: &make_build
  machine:
    image: ubuntu-2204:2022.04.1
  steps:
    - checkout
    - docker/login
    - run: make build package=${PACKAGE}

do_it: &do_it
  jobs:
      - build_php_81
      - build_php_80
      - build_php_74
      - build_docker-with-compose

      - trivy/scan:
          name: "Scan and report security"
          context: 
              - org-global
              - rancher-2
          requires:
            - build_php_81
            - build_php_80
            - build_php_74
            - build_docker-with-compose
          images: '"donkeycode/php-nginx-symfony:8.1-fpm" "donkeycode/php-nginx-symfony:7.4-fpm" "donkeycode/php-nginx-symfony:8.0-fpm" "donkeycode/docker-with-compose"'
          files: ''
          mail_subject: "[PublicImages] Rapport de sécurité post update"
          mail_to: "hosting@donkeycode.com"
      
workflows:
    version: 2.1

    build_push:
      <<: *do_it
      
    build_trigger:
      <<: *do_it
      triggers:
        - schedule:
            # At 04:05 on Monday.
            cron: "5 4 * * 1"
            filters:
                branches:
                    only:
                        - master
        
jobs:
    build_php_81:
      <<: *make_php_symfony
      environment:
        VERSION=8.1

    build_php_80:
      <<: *make_php_symfony
      environment:
        VERSION=8.0

    build_php_74:
      <<: *make_php_symfony
      environment:
        VERSION=7.4

    build_docker-with-compose:
      <<: *make_build
      environment:
        PACKAGE=docker-with-compose
