version: 2.1

orbs: 
  docker: donkeycode/docker@0.0.7

make_php_symfony: &make_php_symfony
  machine:
    image: ubuntu-2004:202010-01 
  steps:
    - checkout
    - run: make build-php-symfony version=${VERSION}

workflows:
    version: 2.1

    build_php:
      # triggers:
      #   - schedule:
      #       # At 04:05 on Monday.
      #       cron: "5 4 * * 1"
      #       filters:
      #           branches:
      #               only:
      #                   - master

      jobs:
        - build_php_81
        
        
jobs:
    build_php_81:
      <<: *make_php_symfony
      environment:
        VERSION=8.1
