version: 2.1

orbs: 
  docker: circleci/docker@2.1.1

make_php_symfony: &make_php_symfony
  executor: docker/docker
  steps:
    - setup_remote_docker
    - checkout
    - run: apk add --no-cache make bash
    - make build-php-symfony version=${VERSION}

workflows:
    version: 2.1

    build_php:
      # triggers:
      #   - schedule:
      #       # At 09:05 on Monday.
      #       cron: "5 9 * * 1"
      #       filters:
      #           branches:
      #               only:
      #                   - master

      jobs:
        - build_php_81
        
        
jobs:
    <<: *make_php_symfony
    environment:
      VERSION=8.1
