FROM elgalu/selenium

USER root
RUN apt-get update && \
    apt-get install -y ruby ruby-dev rubygems libffi-dev clang gcc g++ make mysql-client libmysqld-dev zip && \
    apt-get install -y apt-transport-https ca-certificates curl software-properties-common && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add - && \
    add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" && \
    apt-get update && \
    apt-get install -y docker-ce && \
    curl -L https://github.com/docker/compose/releases/download/1.21.0/docker-compose-$(uname -s)-$(uname -m) -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose && \
    rm -rf /var/lib/apt/lists/*

RUN cd /tmp && curl -o chromedriver_linux64.zip https://chromedriver.storage.googleapis.com/91.0.4472.19/chromedriver_linux64.zip && \
    unzip chromedriver_linux64.zip && \
    rm -f /usr/bin/chromedriver && \
    mv chromedriver /usr/bin/chromedriver

RUN yes | gem uninstall bundler && gem install bundler --no-ri --no-rdoc -v 1.17.1

USER seluser

COPY Gemfile /gems/Gemfile
COPY Gemfile.lock /gems/Gemfile.lock

RUN cd /gems && sudo bundle config cache_path /gems && sudo bundle install

COPY locale.gen  /etc/locale.gen
RUN sudo locale-gen